export const expiry='2026-08-24T23:59:59+04:00';
const q=(id,l,t,x,o,a,type='technical',profile=null)=>({id,level:l,topic:t,question:x,options:o,answer:a,type,profile});
export const bank=[
q('G01',1,'General Accounting','Which statement shows assets, liabilities and equity at a specific date?',['Statement of Financial Position','Statement of Cash Flows','Statement of Profit or Loss'],0),
q('G02',1,'Double Entry','A cash purchase of office supplies is normally recorded as:',['Dr Supplies Expense / Cr Cash','Dr Cash / Cr Supplies Expense','Dr Revenue / Cr Cash'],0),
q('G03',1,'Accruals','An expense incurred but not yet paid should normally be:',['Accrued','Ignored','Recorded as revenue'],0),
q('G04',1,'Prepayments','Insurance paid in advance for future months is initially:',['A prepaid asset','A liability','Revenue'],0),
q('G05',1,'Depreciation','Depreciation primarily allocates:',['The depreciable amount over useful life','Cash payments over useful life','Market value changes'],0),
q('G06',1,'Bank Reconciliation','An unpresented cheque normally explains a difference between:',['Cash book and bank statement','Sales and purchases','Inventory and payroll'],0),
q('G07',1,'UAE VAT','The standard UAE VAT rate is:',['5%','9%','15%'],0),
q('G08',1,'UAE VAT','The general mandatory VAT registration threshold for a UAE-resident business is:',['AED 187,500','AED 375,000','AED 3,000,000'],1),
q('G09',1,'Excel','Which Excel function totals values that meet one condition?',['SUMIF','VLOOKUP','LEFT'],0),
q('G10',1,'Excel','Which reference remains fixed when copied in Excel?',['$A$1','A1','A:A'],0),
q('G11',1,'Outlook','For a finance email requiring follow-up, the best practice is to:',['Flag or create a task with a due date','Mark it unread forever','Forward it repeatedly'],0),
q('G12',1,'AI in Finance','When using AI to draft financial analysis, the accountant should:',['Validate figures and conclusions before use','Assume every output is correct','Upload confidential data to any public tool'],0),
q('S01',2,'IFRS 15','Revenue is generally recognized when:',['Control of promised goods or services transfers','Cash is always received','The invoice is printed'],0),
q('S02',2,'IAS 2','Inventories are generally measured at:',['Lower of cost and net realizable value','Higher of cost and NRV','Selling price only'],0),
q('S03',2,'IAS 16','A significant component of PPE with a different useful life should generally be:',['Depreciated separately','Never depreciated','Expensed immediately in all cases'],0),
q('S04',2,'IAS 37','A provision is recognized when there is a present obligation, probable outflow and:',['A reliable estimate can be made','Management wants a reserve','Cash has already been paid'],0),
q('S05',2,'IFRS 9','Expected credit losses relate primarily to:',['Credit risk on financial assets','Inventory obsolescence','PPE depreciation'],0),
q('S06',2,'Cash Flow','An increase in trade receivables, all else equal, normally:',['Reduces operating cash flow under the indirect method','Increases financing cash flow','Has no cash-flow effect'],0),
q('S07',2,'UAE Corporate Tax','The general UAE Corporate Tax rate on taxable income above the applicable 0% threshold is:',['5%','9%','15%'],1),
q('S08',2,'UAE Corporate Tax','Taxable income commonly starts from:',['Accounting income adjusted under tax rules','Bank balance only','VAT payable only'],0),
q('S09',2,'UAE VAT','Where taxable and exempt activities coexist, input VAT may require:',['Apportionment under applicable rules','Automatic full recovery','Automatic write-off of all VAT'],0),
q('S10',2,'Excel','Which tool is best for repeatable import and transformation of multiple data files?',['Power Query','WordArt','Goal Seek only'],0),
q('S11',2,'Controls','The strongest control over manual journal entries is:',['Documented support, authorization and review','Allowing all users to post','Deleting audit trails'],0),
q('S12',2,'Month End','A good month-end close should include:',['Reconciliations, cut-off review and documented sign-off','Only printing the trial balance','Waiting for the annual audit'],0),
q('C01',3,'IFRS 18','IFRS 18 primarily introduces new requirements for:',['Presentation and disclosure in financial statements','VAT registration','Payroll processing'],0),
q('C02',3,'IFRS 18','IFRS 18 is effective for annual reporting periods beginning on or after:',['1 January 2027','1 January 2025','1 January 2030'],0),
q('C03',3,'IFRS 19','IFRS 19 is designed for eligible subsidiaries without public accountability to:',['Use reduced disclosures while applying IFRS recognition and measurement','Stop applying IFRS','Use cash accounting only'],0),
q('C04',3,'Consolidation','Intercompany balances in consolidated financial statements are generally:',['Eliminated','Doubled','Shown as external revenue'],0),
q('C05',3,'Management Reporting','If profit rises while cash falls, a Chief Accountant should first investigate:',['Working capital and cash conversion','Logo design','Office seating'],0),
q('C06',3,'Controls','A material unreconciled balance before management reporting should be:',['Investigated, quantified and escalated if unresolved','Forced to zero','Hidden until year-end'],0),
q('C07',3,'UAE Corporate Tax','Small Business Relief may generally be available to an eligible Resident Person where revenue does not exceed:',['AED 375,000','AED 3,000,000','AED 10,000,000'],1),
q('C08',3,'Transfer Pricing','Transactions with Related Parties should generally be assessed using:',['The arm’s length principle','VAT invoice sequence only','Cash basis only'],0),
q('C09',3,'UAE VAT','The strongest sales-side VAT control is to:',['Reconcile taxable revenue, VAT codes, invoices, GL and VAT return','Review bank receipts only','Rely entirely on ERP defaults'],0),
q('C10',3,'Excel','For a large recurring management report, the best design is generally:',['Controlled source data plus automated transformations and checks','Manual copy-paste each month','Hard-coded totals'],0),
q('C11',3,'AI Governance','The best finance use of generative AI is:',['Use it with human review, source validation and confidentiality controls','Let it post journals without review','Treat its output as audit evidence by itself'],0),
q('C12',3,'Professional Judgment','A manager asks for an unsupported entry to improve profit. The best response is:',['Decline without adequate support and follow escalation policy','Post it because the manager asked','Post half the amount'],0),
q('A01',4,'Cognitive Reasoning','Sequence: 3, 6, 12, 24, ?',['36','48','54'],1,'cognitive'),
q('A02',4,'Cognitive Reasoning','All invoices are documents. Which statement must be true?',['All documents are invoices','Invoices are documents','No invoices need approval'],1,'cognitive'),
q('A03',4,'Cognitive Reasoning','Which number does not belong: 2, 4, 8, 16, 31, 32?',['31','16','32'],0,'cognitive'),
q('A04',4,'Cognitive Reasoning','4 people complete equal work in 6 hours. At the same rate, 8 people need:',['3 hours','6 hours','12 hours'],0,'cognitive'),
q('A05',4,'Analytical Thinking','Revenue rises from AED 800,000 to AED 920,000. Increase =',['12%','15%','20%'],1,'cognitive'),
q('A06',4,'Analytical Thinking','Margin falls from 25% to 20% while revenue is unchanged. Most likely:',['Costs increased','Revenue doubled','Cash necessarily increased'],0,'cognitive'),
q('A07',4,'Attention to Detail','Which value differs?',['INV-2026-01857','INV-2026-01875','INV-2026-01857'],1,'cognitive'),
q('A08',4,'Attention to Detail','AED 40,000 + 35,450 + 50,000 equals:',['AED 125,450','AED 115,450','AED 135,450'],0,'cognitive'),
q('A09',4,'Problem Solving','Two reports show different revenue for the same period. First:',['Use the higher number','Reconcile definitions, source data, cut-off and filters','Average both'],1,'cognitive'),
q('A10',4,'Problem Solving','A material reconciliation difference appears before deadline. Best action:',['Investigate, quantify impact and escalate if unresolved','Hide it','Force it to zero'],0,'cognitive'),
q('A11',4,'Analytical Thinking','Cash is falling while profit is rising. Investigate first:',['Working capital','Font size','Office attendance'],0,'cognitive'),
q('A12',4,'Professional Judgment','An unsupported profit-improving journal is requested. You should:',['Post it immediately','Decline without support and escalate appropriately','Post half'],1,'cognitive'),
q('B01',4,'Integrity & Ethics','You find a small error in a report already sent. You would:',['Correct it promptly and inform the relevant person','Wait to see if anyone notices','Ignore it'],null,'behavior',{dimension:'Integrity',scores:[3,1,0]}),
q('B02',4,'Ownership','Another department is delaying information you need. You would:',['Follow up early, document dependency and escalate if needed','Wait until deadline','Abandon the task'],null,'behavior',{dimension:'Ownership',scores:[3,1,0]}),
q('B03',4,'Working Under Pressure','Several urgent tasks arrive together. You:',['Prioritize by risk/deadline and communicate','Start the easiest only','Do everything simultaneously without priorities'],null,'behavior',{dimension:'Pressure',scores:[3,1,1]}),
q('B04',4,'Communication','You disagree with an accounting treatment. You:',['Present evidence respectfully','Stay silent regardless of risk','Argue until accepted'],null,'behavior',{dimension:'Communication',scores:[3,0,1]}),
q('B05',4,'Teamwork','A colleague struggles with a close task you know well. You:',['Help while protecting priorities','Ignore them','Take all their work without discussion'],null,'behavior',{dimension:'Teamwork',scores:[3,0,1]}),
q('B06',4,'Attention to Detail','Before submitting an important report you:',['Reconcile key figures and review','Send as soon as formulas calculate','Rely on others to find errors'],null,'behavior',{dimension:'Detail',scores:[3,1,0]}),
q('B07',4,'Adaptability','A new finance system changes a familiar process. You:',['Learn, test and suggest improvements','Refuse to use it','Use it without learning controls'],null,'behavior',{dimension:'Adaptability',scores:[3,0,1]}),
q('B08',4,'Decision Making','Information is incomplete but a decision is needed. You:',['Identify material gaps, assess risk and document judgment','Guess','Avoid deciding indefinitely'],null,'behavior',{dimension:'Judgment',scores:[3,0,1]}),
q('B09',4,'Confidentiality','A colleague without business need asks for salary details. You:',['Decline and follow confidentiality policy','Share because they work here','Share part informally'],null,'behavior',{dimension:'Integrity',scores:[3,0,1]}),
q('B10',4,'Learning Mindset','A tax or accounting rule changes. You:',['Review authoritative guidance and assess impact','Wait for the auditor','Keep old treatment indefinitely'],null,'behavior',{dimension:'Adaptability',scores:[3,1,0]}),
q('B11',4,'Accountability','Your mistake caused a reporting delay. You:',['Acknowledge, correct and propose prevention','Blame the system','Hide the cause'],null,'behavior',{dimension:'Ownership',scores:[3,0,0]}),
q('B12',4,'Professional Conduct','A supplier offers a personal gift during a payment dispute. You:',['Follow ethics/conflict policy and disclose or decline as required','Accept it','Accept and prioritize supplier'],null,'behavior',{dimension:'Integrity',scores:[3,0,0]})
];
export const byId=Object.fromEntries(bank.map(x=>[x.id,x]));
